Load one season and find Texans games

In [1]:
import polars as pl

# Show more rows/columns when displaying a DataFrame (defaults are small)
pl.Config.set_tbl_rows(60)
pl.Config.set_tbl_cols(25)

# Load just ONE season. We're exploring, so we don't need all 770k rows.
# The path starts with ../ because the notebook runs from the notebooks/ folder,
# so we step up one level to the project root first.
pbp = pl.read_parquet("../data/raw/pbp_2025.parquet")

# Find every 2025 game the Texans played (home OR away).
# Every play in a game repeats the same game info, so .unique()
# collapses ~150 rows per game down to one row per game.
hou_games = (
    pbp.filter((pl.col("home_team") == "HOU") | (pl.col("away_team") == "HOU"))
    .select(
        "game_id", "week", "home_team", "away_team",
        "home_score", "away_score",   # final scores
        "spread_line",                # pregame point spread
        "result",                     # final margin
    )
    .unique()
    .sort("week")
)
hou_games

shape: (19, 8)
┌─────────────────┬──────┬───────────┬───────────┬────────────┬────────────┬─────────────┬────────┐
│ game_id         ┆ week ┆ home_team ┆ away_team ┆ home_score ┆ away_score ┆ spread_line ┆ result │
│ ---             ┆ ---  ┆ ---       ┆ ---       ┆ ---        ┆ ---        ┆ ---         ┆ ---    │
│ str             ┆ i32  ┆ str       ┆ str       ┆ i32        ┆ i32        ┆ f64         ┆ i32    │
╞═════════════════╪══════╪═══════════╪═══════════╪════════════╪════════════╪═════════════╪════════╡
│ 2025_01_HOU_LA  ┆ 1    ┆ LA        ┆ HOU       ┆ 14         ┆ 9          ┆ 3.5         ┆ 5      │
│ 2025_02_TB_HOU  ┆ 2    ┆ HOU       ┆ TB        ┆ 19         ┆ 20         ┆ 2.5         ┆ -1     │
│ 2025_03_HOU_JAX ┆ 3    ┆ JAX       ┆ HOU       ┆ 17         ┆ 10         ┆ 1.5         ┆ 7      │
│ 2025_04_TEN_HOU ┆ 4    ┆ HOU       ┆ TEN       ┆ 26         ┆ 0          ┆ 7.5         ┆ 26     │
│ 2025_05_HOU_BAL ┆ 5    ┆ BAL       ┆ HOU       ┆ 10         ┆ 44         ┆ -2.5        ┆ -34    │
│ 2025_07_HOU_SEA ┆ 7    ┆ SEA       ┆ HOU       ┆ 27         ┆ 19         ┆ 3.0         ┆ 8      │
│ 2025_08_SF_HOU  ┆ 8    ┆ HOU       ┆ SF        ┆ 26         ┆ 15         ┆ 2.5         ┆ 11     │
│ 2025_09_DEN_HOU ┆ 9    ┆ HOU       ┆ DEN       ┆ 15         ┆ 18         ┆ 1.5         ┆ -3     │
│ 2025_10_JAX_HOU ┆ 10   ┆ HOU       ┆ JAX       ┆ 36         ┆ 29         ┆ -1.5        ┆ 7      │
│ 2025_11_HOU_TEN ┆ 11   ┆ TEN       ┆ HOU       ┆ 13         ┆ 16         ┆ -5.5        ┆ -3     │
│ 2025_12_BUF_HOU ┆ 12   ┆ HOU       ┆ BUF       ┆ 23         ┆ 19         ┆ -5.5        ┆ 4      │
│ 2025_13_HOU_IND ┆ 13   ┆ IND       ┆ HOU       ┆ 16         ┆ 20         ┆ 3.0         ┆ -4     │
│ 2025_14_HOU_KC  ┆ 14   ┆ KC        ┆ HOU       ┆ 10         ┆ 20         ┆ 4.5         ┆ -10    │
│ 2025_15_ARI_HOU ┆ 15   ┆ HOU       ┆ ARI       ┆ 40         ┆ 20         ┆ 10.5        ┆ 20     │
│ 2025_16_LV_HOU  ┆ 16   ┆ HOU       ┆ LV        ┆ 23         ┆ 21         ┆ 14.5        ┆ 2      │
│ 2025_17_HOU_LAC ┆ 17   ┆ LAC       ┆ HOU       ┆ 16         ┆ 20         ┆ 1.5         ┆ -4     │
│ 2025_18_IND_HOU ┆ 18   ┆ HOU       ┆ IND       ┆ 38         ┆ 30         ┆ 9.5         ┆ 8      │
│ 2025_19_HOU_PIT ┆ 19   ┆ PIT       ┆ HOU       ┆ 6          ┆ 30         ┆ -3.0        ┆ -24    │
│ 2025_20_HOU_NE  ┆ 20   ┆ NE        ┆ HOU       ┆ 28         ┆ 16         ┆ 3.0         ┆ 12     │
└─────────────────┴──────┴───────────┴───────────┴────────────┴────────────┴─────────────┴────────┘

Pull out that game's key columns

In [5]:
GAME_ID = "2025_02_TB_HOU"

# Keep only this game, and only the columns we care about for the model
game = (
    pbp.filter(pl.col("game_id") == GAME_ID)
    .select(
        "qtr",                          # quarter (5 = overtime)
        "game_seconds_remaining",       # time left in the whole game
        "posteam", "defteam",           # who has the ball / who's defending
        "posteam_score", "defteam_score",
        "score_differential",           # score from someone's point of view (which?)
        "down", "ydstogo",              # down and yards to go for a first down
        "yardline_100",                 # field position (measured how?)
        "posteam_timeouts_remaining",
        "defteam_timeouts_remaining",
        "play_type",                    # pass, run, punt, kickoff, no_play...
        "wp",                           # nflfastR's own win probability (our future rival)
        "desc",                         # plain-English description of the play
    )
)

game.head(30)   # the opening of the game

shape: (30, 15)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ qtr ┆ gam ┆ pos ┆ def ┆ pos ┆ def ┆ sco ┆ dow ┆ yds ┆ yar ┆ pos ┆ deftea ┆ play_ ┆ wp    ┆ desc  │
│ --- ┆ e_s ┆ tea ┆ tea ┆ tea ┆ tea ┆ re_ ┆ n   ┆ tog ┆ dli ┆ tea ┆ m_time ┆ type  ┆ ---   ┆ ---   │
│ f64 ┆ eco ┆ m   ┆ m   ┆ m_s ┆ m_s ┆ dif ┆ --- ┆ o   ┆ ne_ ┆ m_t ┆ outs_r ┆ ---   ┆ f64   ┆ str   │
│     ┆ nds ┆ --- ┆ --- ┆ cor ┆ cor ┆ fer ┆ f64 ┆ --- ┆ 100 ┆ ime ┆ emaini ┆ str   ┆       ┆       │
│     ┆ _re ┆ str ┆ str ┆ e   ┆ e   ┆ ent ┆     ┆ f64 ┆ --- ┆ out ┆ ng     ┆       ┆       ┆       │
│     ┆ mai ┆     ┆     ┆ --- ┆ --- ┆ ial ┆     ┆     ┆ f64 ┆ s_r ┆ ---    ┆       ┆       ┆       │
│     ┆ nin ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆     ┆     ┆     ┆ ema ┆ f64    ┆       ┆       ┆       │
│     ┆ g   ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ ini ┆        ┆       ┆       ┆       │
│     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆        ┆       ┆       ┆       │
│     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ 1.0 ┆ 360 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ null   ┆ null  ┆ 0.546 ┆ GAME  │
│     ┆ 0.0 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆        ┆       ┆ 262   ┆       │
│ 1.0 ┆ 360 ┆ HOU ┆ TB  ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ nul ┆ 0.0 ┆ 35. ┆ 3.0 ┆ 3.0    ┆ kicko ┆ 0.546 ┆ 4-C.M │
│     ┆ 0.0 ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ 0   ┆     ┆        ┆ ff    ┆ 262   ┆ cLaug │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ hlin  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ kicks │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 63    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ yards │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 1.0 ┆ 359 ┆ HOU ┆ TB  ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 10. ┆ 64. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.572 ┆ (14:5 │
│     ┆ 3.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 573   ┆ 3)    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 7-C.S │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ troud │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ pass  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ incom │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ p…    │
│ 1.0 ┆ 358 ┆ HOU ┆ TB  ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 2.0 ┆ 10. ┆ 64. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.554 ┆ (14:4 │
│     ┆ 9.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 537   ┆ 9)    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ (Shot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ gun)  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 7-C.S │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ troud │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ p…    │
│ 1.0 ┆ 354 ┆ HOU ┆ TB  ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 3.0 ┆ 1.0 ┆ 55. ┆ 3.0 ┆ 3.0    ┆ run   ┆ 0.563 ┆ (14:0 │
│     ┆ 5.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆        ┆       ┆ 459   ┆ 5)    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 21-N. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ Chubb │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ up    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ the   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ midd… │
│ 1.0 ┆ 350 ┆ HOU ┆ TB  ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 10. ┆ 54. ┆ 3.0 ┆ 3.0    ┆ run   ┆ 0.579 ┆ (13:2 │
│     ┆ 0.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 976   ┆ 0)    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 21-N. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ Chubb │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ up    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ the   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ midd… │
│ 1.0 ┆ 346 ┆ HOU ┆ TB  ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 2.0 ┆ 12. ┆ 56. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.553 ┆ (12:4 │
│     ┆ 5.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 961   ┆ 5)    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ (Shot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ gun)  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 7-C.S │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ troud │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ p…    │
│ 1.0 ┆ 341 ┆ HOU ┆ TB  ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 10. ┆ 29. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.646 ┆ (11:5 │
│     ┆ 8.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 72    ┆ 8)    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ (Shot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ gun)  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 7-C.S │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ troud │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ p…    │
│ 1.0 ┆ 341 ┆ HOU ┆ TB  ┆ 6.0 ┆ 0.0 ┆ 6.0 ┆ nul ┆ 0.0 ┆ 15. ┆ 3.0 ┆ 3.0    ┆ extra ┆ 0.697 ┆ 15-K. │
│     ┆ 3.0 ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ 0   ┆     ┆        ┆ _poin ┆ 489   ┆ Fairb │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆ t     ┆       ┆ airn  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ extra │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ point │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ is …  │
│ 1.0 ┆ 341 ┆ TB  ┆ HOU ┆ 0.0 ┆ 7.0 ┆ -7. ┆ nul ┆ 0.0 ┆ 35. ┆ 3.0 ┆ 3.0    ┆ kicko ┆ 0.300 ┆ 15-K. │
│     ┆ 3.0 ┆     ┆     ┆     ┆     ┆ 0   ┆ l   ┆     ┆ 0   ┆     ┆        ┆ ff    ┆ 705   ┆ Fairb │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ airn  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ kicks │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 65    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ yards │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 1.0 ┆ 341 ┆ TB  ┆ HOU ┆ 0.0 ┆ 7.0 ┆ -7. ┆ 1.0 ┆ 10. ┆ 65. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.319 ┆ (11:5 │
│     ┆ 3.0 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 908   ┆ 3)    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ (Shot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ gun)  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 6-B.M │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ayfie │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ld…   │
│ 1.0 ┆ 340 ┆ TB  ┆ HOU ┆ 0.0 ┆ 7.0 ┆ -7. ┆ 2.0 ┆ 10. ┆ 65. ┆ 3.0 ┆ 3.0    ┆ run   ┆ 0.305 ┆ (11:4 │
│     ┆ 5.0 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 407   ┆ 5)    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ (Shot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ gun)  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 1-R.W │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ hite  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ up…   │
│ 1.0 ┆ 336 ┆ TB  ┆ HOU ┆ 0.0 ┆ 7.0 ┆ -7. ┆ 3.0 ┆ 6.0 ┆ 61. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.300 ┆ (11:0 │
│     ┆ 5.0 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆ 0   ┆     ┆        ┆       ┆ 041   ┆ 5)    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ (Shot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ gun)  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 6-B.M │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ayfie │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ld…   │
│ 1.0 ┆ 332 ┆ TB  ┆ HOU ┆ 0.0 ┆ 7.0 ┆ -7. ┆ 1.0 ┆ 10. ┆ 53. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.337 ┆ (10:2 │
│     ┆ 8.0 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 27    ┆ 8)    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ (Shot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ gun)  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 6-B.M │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ayfie │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ld…   │
│ 1.0 ┆ 332 ┆ TB  ┆ HOU ┆ 0.0 ┆ 7.0 ┆ -7. ┆ 2.0 ┆ 10. ┆ 53. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.322 ┆ (10:2 │
│     ┆ 1.0 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 355   ┆ 1)    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ (Shot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ gun)  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 6-B.M │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ayfie │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ld…   │
│ 1.0 ┆ 328 ┆ TB  ┆ HOU ┆ 0.0 ┆ 7.0 ┆ -7. ┆ 1.0 ┆ 10. ┆ 41. ┆ 3.0 ┆ 3.0    ┆ run   ┆ 0.340 ┆ (9:45 │
│     ┆ 5.0 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 563   ┆ ) (Sh │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ otgun │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ) 7-B │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Irvi │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ng    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ri…   │
│ 1.0 ┆ 324 ┆ TB  ┆ HOU ┆ 0.0 ┆ 7.0 ┆ -7. ┆ 2.0 ┆ 4.0 ┆ 35. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.346 ┆ (9:06 │
│     ┆ 6.0 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆ 0   ┆     ┆        ┆       ┆ 939   ┆ ) 6-B │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Mayf │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ield  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ pass  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ short │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 1.0 ┆ 320 ┆ TB  ┆ HOU ┆ 0.0 ┆ 7.0 ┆ -7. ┆ 1.0 ┆ 10. ┆ 20. ┆ 3.0 ┆ 3.0    ┆ no_pl ┆ 0.377 ┆ (8:23 │
│     ┆ 3.0 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆ ay    ┆ 083   ┆ ) (Sh │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ otgun │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ) 6-B │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Mayf │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ield  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 1.0 ┆ 318 ┆ TB  ┆ HOU ┆ 0.0 ┆ 7.0 ┆ -7. ┆ 1.0 ┆ 20. ┆ 30. ┆ 3.0 ┆ 3.0    ┆ run   ┆ 0.361 ┆ (8:03 │
│     ┆ 3.0 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 614   ┆ ) (Sh │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ otgun │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ) 7-B │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Irvi │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ng    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ri…   │
│ 1.0 ┆ 313 ┆ TB  ┆ HOU ┆ 0.0 ┆ 7.0 ┆ -7. ┆ 2.0 ┆ 10. ┆ 20. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.373 ┆ (7:17 │
│     ┆ 7.0 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 031   ┆ ) (Sh │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ otgun │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ) 6-B │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Mayf │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ield  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 1.0 ┆ 313 ┆ TB  ┆ HOU ┆ 6.0 ┆ 7.0 ┆ -1. ┆ nul ┆ 0.0 ┆ 15. ┆ 3.0 ┆ 3.0    ┆ extra ┆ 0.451 ┆ 4-C.M │
│     ┆ 2.0 ┆     ┆     ┆     ┆     ┆ 0   ┆ l   ┆     ┆ 0   ┆     ┆        ┆ _poin ┆ 531   ┆ cLaug │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆ t     ┆       ┆ hlin  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ extra │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ point │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ is …  │
│ 1.0 ┆ 313 ┆ HOU ┆ TB  ┆ 7.0 ┆ 7.0 ┆ 0.0 ┆ nul ┆ 0.0 ┆ 35. ┆ 3.0 ┆ 3.0    ┆ kicko ┆ 0.546 ┆ 4-C.M │
│     ┆ 2.0 ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ 0   ┆     ┆        ┆ ff    ┆ 262   ┆ cLaug │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ hlin  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ kicks │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 58    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ yards │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 1.0 ┆ 312 ┆ HOU ┆ TB  ┆ 7.0 ┆ 7.0 ┆ 0.0 ┆ 1.0 ┆ 10. ┆ 66. ┆ 3.0 ┆ 3.0    ┆ run   ┆ 0.566 ┆ (7:04 │
│     ┆ 4.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 39    ┆ ) 7-C │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Stro │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ud    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ scram │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ bles  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ri…   │
│ 1.0 ┆ 310 ┆ HOU ┆ TB  ┆ 7.0 ┆ 7.0 ┆ 0.0 ┆ 1.0 ┆ 10. ┆ 59. ┆ 3.0 ┆ 3.0    ┆ run   ┆ 0.575 ┆ (6:42 │
│     ┆ 2.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 369   ┆ ) (Sh │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ otgun │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ) 27- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ W.Mar │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ks    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ up…   │
│ 1.0 ┆ 306 ┆ HOU ┆ TB  ┆ 7.0 ┆ 7.0 ┆ 0.0 ┆ 2.0 ┆ 6.0 ┆ 55. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.569 ┆ (6:03 │
│     ┆ 3.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆        ┆       ┆ 996   ┆ ) (Sh │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ otgun │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ) 7-C │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Stro │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ud    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ pa…   │
│ 1.0 ┆ 301 ┆ HOU ┆ TB  ┆ 7.0 ┆ 7.0 ┆ 0.0 ┆ 1.0 ┆ 10. ┆ 18. ┆ 3.0 ┆ 3.0    ┆ run   ┆ 0.662 ┆ (5:17 │
│     ┆ 7.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 294   ┆ ) 21- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ N.Chu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ bb up │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ the   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ middl │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 1.0 ┆ 298 ┆ HOU ┆ TB  ┆ 7.0 ┆ 7.0 ┆ 0.0 ┆ 2.0 ┆ 2.0 ┆ 10. ┆ 3.0 ┆ 3.0    ┆ no_pl ┆ 0.697 ┆ (4:40 │
│     ┆ 0.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆        ┆ ay    ┆ 95    ┆ ) 21- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ N.Chu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ bb    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ left  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ guard │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ t…    │
│ 1.0 ┆ 295 ┆ HOU ┆ TB  ┆ 7.0 ┆ 7.0 ┆ 0.0 ┆ 2.0 ┆ 12. ┆ 20. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.641 ┆ (4:14 │
│     ┆ 4.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 365   ┆ ) (Sh │

In [6]:
game.tail(25)   # the finish

shape: (25, 15)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ qtr ┆ gam ┆ pos ┆ def ┆ pos ┆ def ┆ sco ┆ dow ┆ yds ┆ yar ┆ pos ┆ deftea ┆ play_ ┆ wp    ┆ desc  │
│ --- ┆ e_s ┆ tea ┆ tea ┆ tea ┆ tea ┆ re_ ┆ n   ┆ tog ┆ dli ┆ tea ┆ m_time ┆ type  ┆ ---   ┆ ---   │
│ f64 ┆ eco ┆ m   ┆ m   ┆ m_s ┆ m_s ┆ dif ┆ --- ┆ o   ┆ ne_ ┆ m_t ┆ outs_r ┆ ---   ┆ f64   ┆ str   │
│     ┆ nds ┆ --- ┆ --- ┆ cor ┆ cor ┆ fer ┆ f64 ┆ --- ┆ 100 ┆ ime ┆ emaini ┆ str   ┆       ┆       │
│     ┆ _re ┆ str ┆ str ┆ e   ┆ e   ┆ ent ┆     ┆ f64 ┆ --- ┆ out ┆ ng     ┆       ┆       ┆       │
│     ┆ mai ┆     ┆     ┆ --- ┆ --- ┆ ial ┆     ┆     ┆ f64 ┆ s_r ┆ ---    ┆       ┆       ┆       │
│     ┆ nin ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆     ┆     ┆     ┆ ema ┆ f64    ┆       ┆       ┆       │
│     ┆ g   ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ ini ┆        ┆       ┆       ┆       │
│     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆        ┆       ┆       ┆       │
│     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ 4.0 ┆ 283 ┆ TB  ┆ HOU ┆ 14. ┆ 13. ┆ 1.0 ┆ 2.0 ┆ 10. ┆ 65. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.639 ┆ (4:43 │
│     ┆ .0  ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 888   ┆ ) (Sh │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ otgun │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ) 6-B │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Mayf │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ield  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 4.0 ┆ 240 ┆ TB  ┆ HOU ┆ 14. ┆ 13. ┆ 1.0 ┆ 3.0 ┆ 8.0 ┆ 63. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.614 ┆ (4:00 │
│     ┆ .0  ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     ┆     ┆ 0   ┆     ┆        ┆       ┆ 77    ┆ ) (Sh │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ otgun │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ) 6-B │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Mayf │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ield  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 4.0 ┆ 198 ┆ TB  ┆ HOU ┆ 14. ┆ 13. ┆ 1.0 ┆ 4.0 ┆ 16. ┆ 71. ┆ 3.0 ┆ 3.0    ┆ punt  ┆ 0.511 ┆ (3:18 │
│     ┆ .0  ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 089   ┆ ) 9-R │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Dixo │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ n     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ punts │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 50    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ yard… │
│ 4.0 ┆ 180 ┆ HOU ┆ TB  ┆ 13. ┆ 14. ┆ -1. ┆ 1.0 ┆ 10. ┆ 26. ┆ 3.0 ┆ 3.0    ┆ run   ┆ 0.676 ┆ (3:00 │
│     ┆ .0  ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 771   ┆ ) 21- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ N.Chu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ bb    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ left  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ tackl │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ e …   │
│ 4.0 ┆ 136 ┆ HOU ┆ TB  ┆ 13. ┆ 14. ┆ -1. ┆ 2.0 ┆ 9.0 ┆ 25. ┆ 3.0 ┆ 3.0    ┆ run   ┆ 0.668 ┆ (2:16 │
│     ┆ .0  ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆     ┆ 0   ┆     ┆        ┆       ┆ 162   ┆ ) 21- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ N.Chu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ bb    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ right │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ guard │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 4.0 ┆ 130 ┆ HOU ┆ TB  ┆ 19. ┆ 14. ┆ 5.0 ┆ nul ┆ 0.0 ┆ 2.0 ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.834 ┆ TWO-P │
│     ┆ .0  ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ l   ┆     ┆     ┆     ┆        ┆       ┆ 925   ┆ OINT  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ CONVE │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ RSION │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ATTEM │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ PT. … │
│ 4.0 ┆ 130 ┆ TB  ┆ HOU ┆ 14. ┆ 19. ┆ -5. ┆ nul ┆ 0.0 ┆ 35. ┆ 3.0 ┆ 3.0    ┆ kicko ┆ 0.204 ┆ 15-K. │
│     ┆ .0  ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆ l   ┆     ┆ 0   ┆     ┆        ┆ ff    ┆ 471   ┆ Fairb │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ airn  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ kicks │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 60    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ yards │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 4.0 ┆ 124 ┆ TB  ┆ HOU ┆ 14. ┆ 19. ┆ -5. ┆ 1.0 ┆ 10. ┆ 80. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.195 ┆ (2:04 │
│     ┆ .0  ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 345   ┆ ) (Sh │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ otgun │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ) 6-B │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Mayf │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ield  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 4.0 ┆ 116 ┆ TB  ┆ HOU ┆ 14. ┆ 19. ┆ -5. ┆ 1.0 ┆ 10. ┆ 68. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.223 ┆ (1:56 │
│     ┆ .0  ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 038   ┆ ) (Sh │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ otgun │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ) 6-B │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Mayf │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ield  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 4.0 ┆ 97. ┆ TB  ┆ HOU ┆ 14. ┆ 19. ┆ -5. ┆ 2.0 ┆ 10. ┆ 68. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.197 ┆ (1:37 │
│     ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 931   ┆ ) (No │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ Huddl │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ e,    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ Shotg │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ un)   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 6-…   │
│ 4.0 ┆ 92. ┆ TB  ┆ HOU ┆ 14. ┆ 19. ┆ -5. ┆ 3.0 ┆ 10. ┆ 68. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.176 ┆ (1:32 │
│     ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 299   ┆ ) (Sh │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ otgun │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ) 6-B │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Mayf │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ield  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 4.0 ┆ 84. ┆ TB  ┆ HOU ┆ 14. ┆ 19. ┆ -5. ┆ 4.0 ┆ 10. ┆ 68. ┆ 3.0 ┆ 3.0    ┆ run   ┆ 0.130 ┆ (1:24 │
│     ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 661   ┆ ) (Sh │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ otgun │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ) 6-B │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .Mayf │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ield  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 4.0 ┆ 59. ┆ TB  ┆ HOU ┆ 14. ┆ 19. ┆ -5. ┆ 1.0 ┆ 10. ┆ 53. ┆ 3.0 ┆ 3.0    ┆ pass  ┆ 0.232 ┆ (:59) │
│     ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 922   ┆ (No   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ Huddl │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ e,    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ Shotg │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ un)   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 6-B…  │
│ 4.0 ┆ 52. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ null   ┆ no_pl ┆ 0.280 ┆ Timeo │
│     ┆ 0   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆        ┆ ay    ┆ 079   ┆ ut #1 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ by    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ HOU   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ at    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 00:52 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .     │
│ 4.0 ┆ 52. ┆ TB  ┆ HOU ┆ 14. ┆ 19. ┆ -5. ┆ 2.0 ┆ 2.0 ┆ 45. ┆ 3.0 ┆ 2.0    ┆ pass  ┆ 0.280 ┆ (:52) │
│     ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆     ┆ 0   ┆     ┆        ┆       ┆ 079   ┆ (Shot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ gun)  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 6-B.M │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ayfie │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ld p… │
│ 4.0 ┆ 42. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ null   ┆ no_pl ┆ 0.422 ┆ Timeo │
│     ┆ 0   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆        ┆ ay    ┆ 262   ┆ ut #1 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ by TB │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ at    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 00:42 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .     │
│ 4.0 ┆ 42. ┆ TB  ┆ HOU ┆ 14. ┆ 19. ┆ -5. ┆ 1.0 ┆ 10. ┆ 23. ┆ 2.0 ┆ 2.0    ┆ pass  ┆ 0.422 ┆ (:42) │
│     ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆        ┆       ┆ 262   ┆ (Shot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ gun)  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 6-B.M │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ayfie │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ld p… │
│ 4.0 ┆ 34. ┆ TB  ┆ HOU ┆ 14. ┆ 19. ┆ -5. ┆ 2.0 ┆ 5.0 ┆ 18. ┆ 2.0 ┆ 2.0    ┆ pass  ┆ 0.429 ┆ (:34) │
│     ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆     ┆ 0   ┆     ┆        ┆       ┆ 115   ┆ (Shot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ gun)  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 6-B.M │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ayfie │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ld p… │
│ 4.0 ┆ 13. ┆ TB  ┆ HOU ┆ 14. ┆ 19. ┆ -5. ┆ 1.0 ┆ 7.0 ┆ 7.0 ┆ 2.0 ┆ 2.0    ┆ pass  ┆ 0.449 ┆ (:13) │
│     ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆        ┆       ┆ 164   ┆ (No   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ Huddl │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ e,    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ Shotg │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ un)   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 6-B…  │
│ 4.0 ┆ 9.0 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ null   ┆ no_pl ┆ 0.419 ┆ Timeo │
│     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆        ┆ ay    ┆ 243   ┆ ut #2 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ by    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ HOU   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ at    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 00:09 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .     │
│ 4.0 ┆ 9.0 ┆ TB  ┆ HOU ┆ 14. ┆ 19. ┆ -5. ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 1.0    ┆ run   ┆ 0.419 ┆ (:09) │
│     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆        ┆       ┆ 243   ┆ 1-R.W │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ hite  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ right │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ guard │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ fo…   │
│ 4.0 ┆ 6.0 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ null   ┆ no_pl ┆ 0.779 ┆ Timeo │
│     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆        ┆ ay    ┆ 091   ┆ ut #2 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ by TB │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ at    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 00:06 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ .     │
│ 4.0 ┆ 6.0 ┆ TB  ┆ HOU ┆ 20. ┆ 19. ┆ 1.0 ┆ nul ┆ 0.0 ┆ 2.0 ┆ 1.0 ┆ 1.0    ┆ pass  ┆ 0.779 ┆ TWO-P │
│     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ l   ┆     ┆     ┆     ┆        ┆       ┆ 091   ┆ OINT  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ CONVE │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ RSION │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ ATTEM │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ PT. … │
│ 4.0 ┆ 6.0 ┆ HOU ┆ TB  ┆ 19. ┆ 20. ┆ -1. ┆ nul ┆ 0.0 ┆ 35. ┆ 1.0 ┆ 1.0    ┆ kicko ┆ 0.319 ┆ 4-C.M │
│     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆ l   ┆     ┆ 0   ┆     ┆        ┆ ff    ┆ 726   ┆ cLaug │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ hlin  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ kicks │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ 61    │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ yards │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆ …     │
│ 4.0 ┆ 0.0 ┆ HOU ┆ TB  ┆ 19. ┆ 20. ┆ -1. ┆ nul ┆ 0.0 ┆ nul ┆ 1.0 ┆ 1.0    ┆ null  ┆ null  ┆ END   │
│     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆ l   ┆     ┆ l   ┆     ┆        ┆       ┆       ┆ GAME  │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┘